### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by rianquinn** [nopjne/EntityHero#4]
Love this tool. It would be great if there were two features added:
- Multiple Selections (either the ability to select a block with shift or individual items with ctrl)
- Ctrl+S save support (lost some changes to this missing)

**Comment by rianquinn** [comment]
- Ctrl+F to find "next" would be great too

**Comment by nopjne** [comment]
Thanks! I appreciate any interest in this tool.

ctrl+s should already be present.
https://github.com/nopjne/EntityHero/blob/465d835b16c3832c43cb6ae7acd5df447469b01c/wxGUI/dataview.cpp#L1020
If there is a bug could you provide repro steps? That way I can attempt to fix on my end.

Will definitely add ctrl+f, great suggestion.

Multi select is probably a bit out, as it does not fit well with the way I expect people to edit these files. You can always select the parent node (of the things you are interested in) and copy/move or paste that.

**Comment by nopjne** [comment]
Added CTRL+F https://github.com/nopjne/EntityHero/commit/26411a68042d3154e9a093ca17eff0b917425d5c
