### ISSUE TITLE
New version load bug

### ISSUE THREAD

**Issue by Moiras** [nopjne/EntityHero#8]
Hi, i downloaded the last version but I get this error when I open the entities file from MH and then Save and reload the level (even if I don't change anything). This window pops up and then DOOM crashes. I also can't use the GoToReference function, as it's not able to find any entityDefs

![error](https://user-images.githubusercontent.com/40225913/114431091-7cbb1580-9b95-11eb-9293-a8e7d3c24b95.png)

**Comment by nopjne** [comment]
Could you try 0.8.2? Let me know if its fixed.

**Comment by Moiras** [comment]
Yes it works now!
Thank You very much :)

**Comment by nopjne** [comment]
Fixed by: e5c79f50780e0af1e3093f6a87629123b71aecb7
